import { ScopevisioError } from "./client";
import type { ScopevisioContext } from "./context";
import type { InvoiceDraft } from "./types";

/**
 * Booking a sale as journal postings — the working alternative to the blocked
 * document import.
 *
 * `POST /postings/new` is JSON, documented, and takes `autoCreateTax` so the
 * ERP generates the VAT row from the `vatKey` rather than us computing it.
 * A sales invoice is the classic two-row booking (SKR03):
 *
 *   Debitor 10046 (Sammelkonto 1400)   119.00  debit
 *   Erlöse  8400                       100.00  credit   vatKey U19
 *   → USt 19.00 credit, generated by autoCreateTax
 *
 * WHAT THIS GIVES YOU: the revenue and the receivable land in the ledger,
 * correctly classified, with the Shopify order id on the booking. That is the
 * accounting outcome the PRD is actually after.
 *
 * WHAT IT DOES NOT GIVE YOU: a Faktura *document* — no Belegnummer in the
 * invoice range, no PDF, no document layout. Shopify already sends the buyer
 * their own confirmation, so for a shop this is usually acceptable; for a
 * merchant who needs a Scopevisio-rendered invoice PDF it is not.
 *
 * ⚠️ A posting is committed to the ledger immediately. Under GoBD it cannot be
 * deleted — only reversed with a Storno (`/posting/cancel`,
 * `/postings/correction`). So this path must only run when the merchant has
 * explicitly chosen it, and never as a silent fallback.
 */

export interface PostingRow {
  postingDate: number;
  documentDate?: number;
  documentNumber: string;
  externalDocumentNumber?: string;
  account: string;
  summaryAccount?: string;
  amount: number;
  vatKey?: string;
  documentText?: string;
  rowText?: string;
  ustId?: string;
  paymentType?: string;
}

export interface PostingsPayload {
  adjustVatKey?: boolean;
  autoCreateTax?: boolean;
  rows: PostingRow[];
}

export interface PostingSettings {
  /** Sammelkonto for debitors — 1400 in SKR03, 10000 in SKR04. */
  debitorSummaryAccount: string;
  /** Let the ERP generate the VAT row from the vatKey. */
  autoCreateTax: boolean;
}

export interface BuildPostingsArgs {
  draft: InvoiceDraft;
  documentNumber: string;
  grossCents: number;
  netCents: number;
  settings: PostingSettings;
}

/**
 * Build the booking. Debit is positive, credit negative — the convention the
 * import expects, and the reason the rows must sum to zero once the generated
 * tax row is included.
 */
export function buildPostings(args: BuildPostingsArgs): PostingsPayload {
  const { draft, settings } = args;

  if (!draft.personalAccount) {
    throw new ScopevisioError(
      "The customer has no Scopevisio debitor account, so the sale cannot be booked.",
      undefined,
      undefined,
      true,
    );
  }
  if (!draft.account) {
    throw new ScopevisioError(
      "No Erlöskonto was resolved for this order, so the sale cannot be booked.",
      undefined,
      undefined,
      true,
    );
  }

  const postingDate = parseGermanDate(draft.documentDate);
  const text = draft.externalRef ? `Shopify ${draft.externalRef}` : "Shopify order";

  return {
    autoCreateTax: settings.autoCreateTax,
    // Trust the Erlöskonto's own vatKey over anything we supply.
    adjustVatKey: false,
    rows: [
      {
        // Receivable against the customer.
        postingDate,
        documentDate: postingDate,
        documentNumber: args.documentNumber,
        externalDocumentNumber: draft.externalId,
        account: draft.personalAccount,
        summaryAccount: settings.debitorSummaryAccount,
        amount: round2(args.grossCents / 100),
        documentText: text,
        rowText: text,
      },
      {
        // Revenue, with the tax key that drives the generated VAT row.
        postingDate,
        documentDate: postingDate,
        documentNumber: args.documentNumber,
        externalDocumentNumber: draft.externalId,
        account: draft.account,
        amount: -round2(args.netCents / 100),
        vatKey: draft.vatKey ?? undefined,
        documentText: text,
        rowText: text,
      },
    ],
  };
}

export interface PostingsResult {
  ok: boolean;
  documentNumber: string;
  raw: unknown;
}

/**
 * Send the booking. Irreversible — the caller must have established that the
 * merchant chose this mode and that the tax cross-check passed.
 */
export async function bookPostings(
  ctx: ScopevisioContext,
  payload: PostingsPayload,
  documentNumber: string,
): Promise<PostingsResult> {
  const client = ctx.client;

  const raw = await client.post<Record<string, unknown>>("/postings/new", payload);

  // Mirror the import endpoint's lesson: never treat a 200 as success without
  // evidence. Anything that reads as an error message is a failure.
  const asText = JSON.stringify(raw ?? {});
  const failed =
    /error|fehler|invalid|ungültig|not\s+found|nicht\s+gefunden/i.test(asText) &&
    !/errors?"\s*:\s*(\[\]|null|0)/i.test(asText);

  if (failed) {
    throw new ScopevisioError(
      `Scopevisio rejected the booking: ${asText.slice(0, 400)}`,
      undefined,
      asText,
      true,
    );
  }

  await ctx.journal.event({
    event: "postings.booked",
    externalId: payload.rows[0]?.externalDocumentNumber ?? null,
    message: `Booked ${documentNumber} as journal postings (${payload.rows.length} rows).`,
    data: { documentNumber, rows: payload.rows.length, response: raw },
  });

  return { ok: true, documentNumber, raw };
}

/**
 * Document numbers must be unique and traceable. The Shopify order name is
 * both, and re-deriving it means a retry reuses the same number rather than
 * creating a second booking.
 */
export function documentNumberForOrder(draft: InvoiceDraft): string {
  const base = (draft.externalRef ?? draft.externalId.split("/").pop() ?? "SHOP")
    .replace(/[^A-Za-z0-9-]/g, "")
    .slice(0, 20);
  return base || "SHOP";
}

function parseGermanDate(value: string): number {
  const [dd, mm, yyyy] = value.split(".").map(Number);
  if (!dd || !mm || !yyyy) return Date.now();
  return Date.UTC(yyyy, mm - 1, dd);
}

function round2(value: number): number {
  return Math.round(value * 100) / 100;
}
