import crypto from "node:crypto";

/**
 * Shopware's app handshake and every webhook it sends are authenticated with
 * SHA-256 HMACs. Three different secrets are in play and mixing them up is the
 * classic way to spend a day on a 401:
 *
 *   - the APP secret   — shared between Shopware and us, fixed in manifest.xml.
 *                        Signs the initial registration request.
 *   - the SHOP secret  — generated by us, per shop, during registration.
 *                        Signs the confirmation request and every webhook.
 *   - the API key/pair — Admin API credentials, not used for signing at all.
 *
 * Kept free of I/O so it can be tested exhaustively.
 */

/** SHA-256 HMAC, hex-encoded, as Shopware computes it. */
export function hmac(payload: string, secret: string): string {
  return crypto.createHmac("sha256", secret).update(payload, "utf8").digest("hex");
}

/**
 * Constant-time comparison.
 *
 * `crypto.timingSafeEqual` throws when the buffers differ in length, which for
 * a signature check is itself an answer — so length mismatch returns false
 * rather than propagating.
 */
export function safeEqual(a: string, b: string): boolean {
  const ba = Buffer.from(a, "utf8");
  const bb = Buffer.from(b, "utf8");
  if (ba.length !== bb.length) return false;
  return crypto.timingSafeEqual(ba, bb);
}

/** Verify a signature header against a payload. */
export function verify(payload: string, signature: string | undefined, secret: string): boolean {
  if (!signature) return false;
  return safeEqual(hmac(payload, secret), signature);
}

/**
 * The proof Shopware requires in the registration response: HMAC of
 * shopId + shopUrl + appName, signed with the app secret.
 *
 * Concatenated with no separator — that is what Shopware computes, and adding
 * one produces a proof that is silently rejected.
 */
export function registrationProof(args: {
  shopId: string;
  shopUrl: string;
  appName: string;
  appSecret: string;
}): string {
  return hmac(args.shopId + args.shopUrl + args.appName, args.appSecret);
}

/**
 * The per-shop secret we hand back during registration. Shopware requires
 * 64–255 characters; 64 bytes of randomness hex-encoded gives 128.
 */
export function generateShopSecret(): string {
  return crypto.randomBytes(64).toString("hex");
}

/**
 * The registration request is signed over the query string.
 *
 * Shopware signs the query string as it sent it, so it must be reconstructed
 * from the raw URL rather than re-encoded from parsed parameters — round-trips
 * through URLSearchParams reorder and re-escape, and the HMAC then fails for
 * reasons that look like a wrong secret.
 */
export function rawQueryString(url: string): string {
  const i = url.indexOf("?");
  return i === -1 ? "" : url.slice(i + 1);
}
